---
# tasks file for jq - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Installing {{ jq_app }}
  ansible.builtin.apt:
    name: "{{ jq_app }}"
    state: "{{ jq_desired_state }}"
    force_apt_get: yes
    update_cache: yes
