---
# tasks file for jq - Debian family

- name: "Installing {{ jq_app }} on Debian based systems."
  apt:
    name: "{{ jq_app }}"
    state: "{{ jq_desired_state }}"
    force_apt_get: yes
    update_cache: yes
